version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: inshape_postgres
    environment:
      POSTGRES_DB: inshape
      POSTGRES_USER: inshape_user
      POSTGRES_PASSWORD: inshape_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
